# Generated by Django 5.2.3 on 2025-06-12 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talent_management', '0002_remove_resume_certifications_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='resume_pdf',
            field=models.FileField(blank=True, null=True, upload_to='resumes/'),
        ),
    ]
