# Generated by Django 5.2.3 on 2025-06-13 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talent_management', '0004_alter_resume_aadhar_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certification',
            name='name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='resume',
            name='name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='skill',
            name='name',
            field=models.TextField(),
        ),
    ]
