# Generated by Django 5.2.3 on 2025-06-13 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talent_management', '0008_remove_resume_resume_pdf_resume_awards_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='preferred_location',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='resume',
            name='resume_pdf',
            field=models.FileField(blank=True, null=True, upload_to='resumes/'),
        ),
        migrations.AddField(
            model_name='resume',
            name='work_arrangement',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
