# Generated by Django 5.2.3 on 2025-06-15 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talent_management', '0010_resume_degree_institution_name_resume_degree_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resume',
            options={'verbose_name': 'Resume', 'verbose_name_plural': 'Resumes'},
        ),
        migrations.AddField(
            model_name='resume',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
