# Generated by Django 5.2.3 on 2025-07-11 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talent_management', '0016_resume_frameworks_tools'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='certification_details',
            field=models.JSONField(blank=True, default=list, verbose_name='Certification Details'),
        ),
        migrations.AddField(
            model_name='resume',
            name='certification_photos',
            field=models.JSONField(blank=True, default=list, verbose_name='Certification Photos'),
        ),
        migrations.AddField(
            model_name='resume',
            name='current_area',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='resume',
            name='current_city',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='resume',
            name='current_country',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='resume',
            name='current_district',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='resume',
            name='current_state',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='resume',
            name='degree_details',
            field=models.JSONField(blank=True, default=list, verbose_name='Degree Details'),
        ),
        migrations.AddField(
            model_name='resume',
            name='diploma_details',
            field=models.JSONField(blank=True, default=list, verbose_name='Diploma Details'),
        ),
        migrations.AddField(
            model_name='resume',
            name='permanent_area',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='resume',
            name='permanent_city',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='resume',
            name='permanent_country',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='resume',
            name='permanent_district',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='resume',
            name='permanent_state',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='resume',
            name='professional_links',
            field=models.JSONField(blank=True, default=list, verbose_name='Professional Links'),
        ),
        migrations.AddField(
            model_name='resume',
            name='work_authorizations',
            field=models.JSONField(blank=True, default=list, verbose_name='Work Authorizations'),
        ),
        migrations.AddField(
            model_name='resume',
            name='work_preferences',
            field=models.JSONField(blank=True, default=list, verbose_name='Work Preferences'),
        ),
    ]
