# Generated by Django 5.2.3 on 2025-08-07 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talent_management', '0020_trendingskill'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TrendingSkill',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='aadhar_number',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='certifications',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='criminal_record_disclosure',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='current_location',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='degree_institution_name',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='degree_name',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='degree_result_upload',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='degree_score',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='degree_specialization',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='degree_year_passing',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='diploma_course_name',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='diploma_institution_name',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='diploma_result_upload',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='diploma_score',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='diploma_year_passing',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='document_verification',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='frameworks_tools',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='github_url',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='linkedin_url',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='medium_or_blog_url',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='passport_number',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='portfolio_url',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='preferences',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='stackoverflow_url',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='work_arrangement',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='work_authorization',
        ),
        migrations.AddField(
            model_name='resume',
            name='domain_interest',
            field=models.CharField(blank=True, choices=[('AI_ML_ENGINEER', 'AI/ML Engineer'), ('DATA_SCIENTIST', 'Data Scientist'), ('BUSINESS_ANALYST', 'Business Analyst')], max_length=50, null=True, verbose_name='Domain of Interest'),
        ),
        migrations.AddField(
            model_name='resume',
            name='employee_level',
            field=models.CharField(blank=True, choices=[('FRESHER', 'Fresher'), ('INTERN', 'Intern'), ('EXPERIENCED', 'Experienced')], max_length=50, null=True, verbose_name='Employee Level'),
        ),
        migrations.AddField(
            model_name='resume',
            name='is_fresher',
            field=models.BooleanField(default=False, verbose_name='Is Fresher'),
        ),
    ]
