# Generated by Django 5.2.3 on 2025-06-13 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talent_management', '0003_alter_resume_resume_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='aadhar_number',
            field=models.CharField(blank=True, default='Not Provided', max_length=12),
        ),
        migrations.AlterField(
            model_name='resume',
            name='current_company',
            field=models.CharField(blank=True, default='Not Provided', max_length=100),
        ),
        migrations.AlterField(
            model_name='resume',
            name='current_location',
            field=models.CharField(blank=True, default='Not Provided', max_length=100),
        ),
        migrations.AlterField(
            model_name='resume',
            name='document_verification',
            field=models.TextField(blank=True, default='Incomplete'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='generated_preferences',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='resume',
            name='generated_summary',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='resume',
            name='github_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='resume',
            name='linkedin_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='resume',
            name='passport_number',
            field=models.CharField(blank=True, default='Not Provided', max_length=20),
        ),
        migrations.AlterField(
            model_name='resume',
            name='preferences',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='resume',
            name='resume_pdf',
            field=models.FileField(default='', upload_to='resumes/'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='summary',
            field=models.TextField(blank=True, default=''),
        ),
    ]
