# Generated by Django 5.2.3 on 2025-06-13 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('talent_management', '0006_remove_experience_resume_remove_project_resume_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='achievements',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='education',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='languages',
        ),
    ]
