# Generated by Django 5.2.3 on 2025-06-13 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talent_management', '0007_remove_resume_achievements_remove_resume_education_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='resume_pdf',
        ),
        migrations.AddField(
            model_name='resume',
            name='awards',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='resume',
            name='criminal_record_disclosure',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='resume',
            name='dev_environment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='resume',
            name='extracurriculars',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='resume',
            name='languages',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='resume',
            name='medium_or_blog_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='resume',
            name='open_source_contributions',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='resume',
            name='portfolio_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='resume',
            name='preferred_tech_stack',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='resume',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='profile_photos/'),
        ),
        migrations.AddField(
            model_name='resume',
            name='publications',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='resume',
            name='references',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='resume',
            name='stackoverflow_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='resume',
            name='volunteering_experience',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='resume',
            name='work_authorization',
            field=models.TextField(blank=True, default=''),
        ),
    ]
