# Generated by Django 5.2.3 on 2025-06-15 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talent_management', '0009_resume_preferred_location_resume_resume_pdf_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='degree_institution_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Degree Institution Name'),
        ),
        migrations.AddField(
            model_name='resume',
            name='degree_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Degree Name'),
        ),
        migrations.AddField(
            model_name='resume',
            name='degree_result_upload',
            field=models.FileField(blank=True, null=True, upload_to='education_results/degree/', verbose_name='Degree Result Upload'),
        ),
        migrations.AddField(
            model_name='resume',
            name='degree_score',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Degree Score/Grade'),
        ),
        migrations.AddField(
            model_name='resume',
            name='degree_specialization',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Degree Specialization'),
        ),
        migrations.AddField(
            model_name='resume',
            name='degree_year_passing',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Degree Year Passing'),
        ),
        migrations.AddField(
            model_name='resume',
            name='diploma_course_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Diploma Course Name'),
        ),
        migrations.AddField(
            model_name='resume',
            name='diploma_institution_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Diploma Institution Name'),
        ),
        migrations.AddField(
            model_name='resume',
            name='diploma_result_upload',
            field=models.FileField(blank=True, null=True, upload_to='education_results/diploma/', verbose_name='Diploma Result Upload'),
        ),
        migrations.AddField(
            model_name='resume',
            name='diploma_score',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Diploma Score/Grade'),
        ),
        migrations.AddField(
            model_name='resume',
            name='diploma_year_passing',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Diploma Year Passing'),
        ),
        migrations.AddField(
            model_name='resume',
            name='tenth_board_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='10th Board Name'),
        ),
        migrations.AddField(
            model_name='resume',
            name='tenth_result_upload',
            field=models.FileField(blank=True, null=True, upload_to='education_results/10th/', verbose_name='10th Result Upload'),
        ),
        migrations.AddField(
            model_name='resume',
            name='tenth_school_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='10th School Name'),
        ),
        migrations.AddField(
            model_name='resume',
            name='tenth_score',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='10th Score/Grade'),
        ),
        migrations.AddField(
            model_name='resume',
            name='tenth_year_passing',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='10th Year Passing'),
        ),
        migrations.AddField(
            model_name='resume',
            name='twelfth_board_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='12th Board Name'),
        ),
        migrations.AddField(
            model_name='resume',
            name='twelfth_college_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='12th College Name'),
        ),
        migrations.AddField(
            model_name='resume',
            name='twelfth_result_upload',
            field=models.FileField(blank=True, null=True, upload_to='education_results/12th/', verbose_name='12th Result Upload'),
        ),
        migrations.AddField(
            model_name='resume',
            name='twelfth_score',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='12th Score/Grade'),
        ),
        migrations.AddField(
            model_name='resume',
            name='twelfth_year_passing',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='12th Year Passing'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='resume',
            name='phone',
            field=models.CharField(max_length=20),
        ),
    ]
