# Generated by Django 5.2.3 on 2025-06-18 06:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talent_management', '0012_joblisting'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='talent_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resumes', to=settings.AUTH_USER_MODEL),
        ),
    ]
