# Generated by Django 5.2.3 on 2025-06-19 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talent_management', '0013_resume_talent_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employerprofile',
            name='industry',
            field=models.CharField(blank=True, choices=[('IT_SOFTWARE', 'IT/Software'), ('FINANCE', 'Finance'), ('HEALTHCARE', 'Healthcare'), ('EDUCATION', 'Education'), ('MANUFACTURING', 'Manufacturing'), ('RETAIL', 'Retail'), ('CONSULTING', 'Consulting'), ('MEDIA_ENTERTAINMENT', 'Media & Entertainment'), ('HOSPITALITY', 'Hospitality'), ('CONSTRUCTION', 'Construction'), ('GOVERNMENT', 'Government'), ('NON_PROFIT', 'Non-Profit'), ('E_COMMERCE', 'E-commerce'), ('TELECOMMUNICATIONS', 'Telecommunications'), ('AUTOMOTIVE', 'Automotive'), ('PHARMACEUTICALS', 'Pharmaceuticals'), ('ENERGY', 'Energy'), ('TRANSPORTATION_LOGISTICS', 'Transportation & Logistics'), ('FOOD_BEVERAGE', 'Food & Beverage'), ('REAL_ESTATE', 'Real Estate'), ('MARKETING_ADVERTISING', 'Marketing & Advertising'), ('OTHER', 'Other')], max_length=100, null=True, verbose_name='Industry'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='document_verification',
            field=models.CharField(choices=[('INCOMPLETE', 'Incomplete'), ('PENDING_REVIEW', 'Pending Review'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected'), ('NOT_APPLICABLE', 'Not Applicable')], default='INCOMPLETE', max_length=50, verbose_name='Document Verification Status'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='work_arrangement',
            field=models.CharField(blank=True, choices=[('FULL_TIME', 'Full-time'), ('PART_TIME', 'Part-time'), ('CONTRACT', 'Contract'), ('TEMPORARY', 'Temporary'), ('FREELANCE', 'Freelance'), ('INTERNSHIP', 'Internship'), ('VOLUNTEER', 'Volunteer'), ('GIG', 'Gig'), ('REMOTE', 'Remote'), ('HYBRID', 'Hybrid')], max_length=50, null=True, verbose_name='Preferred Work Arrangement'),
        ),
    ]
