# Generated by Django 5.2.3 on 2025-06-16 09:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talent_management', '0011_alter_resume_options_resume_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Job Title')),
                ('company_name', models.CharField(max_length=255, verbose_name='Company Name')),
                ('description', models.TextField(verbose_name='Job Description')),
                ('requirements', models.TextField(blank=True, null=True, verbose_name='Job Requirements')),
                ('industry', models.CharField(blank=True, max_length=100, null=True, verbose_name='Industry')),
                ('location', models.CharField(blank=True, max_length=255, null=True, verbose_name='Job Location')),
                ('salary_min', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Minimum Salary')),
                ('salary_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Maximum Salary')),
                ('currency', models.CharField(blank=True, max_length=10, null=True, verbose_name='Currency')),
                ('base_salary_unit', models.CharField(blank=True, max_length=50, null=True, verbose_name='Salary Unit')),
                ('employment_type', models.CharField(blank=True, choices=[('FULL_TIME', 'Full-time'), ('PART_TIME', 'Part-time'), ('CONTRACT', 'Contract'), ('TEMPORARY', 'Temporary'), ('INTERNSHIP', 'Internship'), ('VOLUNTEER', 'Volunteer')], max_length=50, null=True, verbose_name='Employment Type')),
                ('work_location_type', models.CharField(blank=True, choices=[('REMOTE', 'Remote'), ('ONSITE', 'On-site'), ('HYBRID', 'Hybrid')], max_length=50, null=True, verbose_name='Work Location Type')),
                ('hiring_organization_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='Hiring Org URL')),
                ('hiring_organization_logo', models.URLField(blank=True, max_length=500, null=True, verbose_name='Hiring Org Logo')),
                ('external_application_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='External Application URL')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Publication Date')),
                ('external_source_id', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='External Source ID')),
                ('external_source_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='External Source Name')),
                ('status', models.CharField(choices=[('PENDING', 'Pending Verification'), ('VERIFIED', 'Verified & Active'), ('REJECTED', 'Rejected'), ('CLOSED', 'Closed'), ('EXPIRED', 'Expired')], default='PENDING', max_length=50, verbose_name='Job Status')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='Verification Timestamp')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation Timestamp')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Updated Timestamp')),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posted_jobs', to=settings.AUTH_USER_MODEL, verbose_name='Posted By')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_jobs', to=settings.AUTH_USER_MODEL, verbose_name='Verified By')),
            ],
            options={
                'verbose_name': 'Job Listing',
                'verbose_name_plural': 'Job Listings',
                'ordering': ['-created_at'],
            },
        ),
    ]
