# Generated by Django 5.2.3 on 2025-07-09 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talent_management', '0015_resume_is_deleted_alter_customuser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='frameworks_tools',
            field=models.JSONField(blank=True, default=list, verbose_name='Frameworks & Tools'),
        ),
    ]
