# Generated by Django 5.2.3 on 2025-07-21 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talent_management', '0017_resume_certification_details_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrendingSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(max_length=100, unique=True, verbose_name='Skill Name')),
                ('demand', models.CharField(blank=True, max_length=20, verbose_name='Demand Percentage')),
                ('increase', models.CharField(blank=True, max_length=20, verbose_name='Increase Over Last Year')),
                ('priority', models.CharField(blank=True, max_length=50, verbose_name='Priority Level')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Trending Skill',
                'verbose_name_plural': 'Trending Skills',
                'ordering': ['id'],
            },
        ),
    ]
