# Generated by Django 5.2.3 on 2025-07-24 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talent_management', '0018_trendingskill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joblisting',
            name='currency',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Currency'),
        ),
        migrations.AlterField(
            model_name='joblisting',
            name='salary_max',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True, verbose_name='Maximum Salary'),
        ),
        migrations.AlterField(
            model_name='joblisting',
            name='salary_min',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True, verbose_name='Minimum Salary'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='degree_score',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Degree Score/Grade'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='degree_year_passing',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Degree Year Passing'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='diploma_score',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Diploma Score/Grade'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='diploma_year_passing',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Diploma Year Passing'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='tenth_board_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='10th Board Name'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='tenth_score',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='10th Score/Grade'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='tenth_year_passing',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='10th Year Passing'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='twelfth_board_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='12th Board Name'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='twelfth_score',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='12th Score/Grade'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='twelfth_year_passing',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='12th Year Passing'),
        ),
    ]
