# Generated by Django 5.2.3 on 2025-08-04 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talent_management', '0019_alter_customuser_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrendingSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(default='AI/ML Engineer', max_length=255)),
                ('skill', models.CharField(max_length=255)),
                ('demand', models.CharField(blank=True, max_length=50)),
                ('increase', models.CharField(blank=True, max_length=50)),
                ('priority', models.CharField(blank=True, max_length=50)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['role', '-priority'],
                'unique_together': {('role', 'skill')},
            },
        ),
    ]
