# Generated by Django 5.2.3 on 2025-07-25 09:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talent_management', '0019_alter_joblisting_currency_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MockInterviewResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interview_start_time', models.DateTimeField(auto_now_add=True)),
                ('interview_end_time', models.DateTimeField(blank=True, null=True)),
                ('position_applied', models.CharField(max_length=255, verbose_name='Position Applied For')),
                ('candidate_experience', models.TextField(verbose_name='Candidate Experience Description')),
                ('communication_overall_score', models.IntegerField(default=0, verbose_name='Communication Overall Score')),
                ('psychometric_overall_score', models.IntegerField(default=0, verbose_name='Psychometric Overall Score')),
                ('aiml_specialization_input', models.CharField(blank=True, max_length=255, null=True, verbose_name='AIML Specialization Input')),
                ('aiml_specialization', models.JSONField(blank=True, default=list, null=True, verbose_name='AIML Specialization Details')),
                ('pre_generated_questions_data', models.JSONField(blank=True, default=dict, null=True, verbose_name='Pre-Generated Questions Data')),
                ('full_qa_transcript', models.JSONField(blank=True, default=list, null=True, verbose_name='Full Q&A Transcript')),
                ('technical_specialization_scores', models.JSONField(blank=True, default=dict, null=True, verbose_name='Technical Specialization Scores')),
                ('identity_verified', models.BooleanField(default=False, verbose_name='Identity Verified')),
                ('malpractice_detected', models.BooleanField(default=False, verbose_name='Malpractice Detected')),
                ('malpractice_reason', models.TextField(blank=True, null=True, verbose_name='Malpractice Reason')),
                ('global_readiness_score', models.IntegerField(default=0, verbose_name='Global Readiness Score')),
                ('language_proficiency_score', models.IntegerField(default=0, verbose_name='Language Proficiency Score')),
                ('language_analysis', models.TextField(blank=True, null=True, verbose_name='Language Analysis')),
                ('round_analysis_json', models.JSONField(blank=True, default=dict, null=True, verbose_name='Detailed Round Analysis (JSON)')),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed Successfully'), ('TERMINATED_MALPRACTICE', 'Terminated Due to Malpractice'), ('TERMINATED_ERROR', 'Terminated Due to Error'), ('TERMINATED_MANUAL', 'Manually Terminated')], default='IN_PROGRESS', max_length=50, verbose_name='Interview Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mock_interview_results', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mock Interview Result',
                'verbose_name_plural': 'Mock Interview Results',
                'ordering': ['-interview_start_time'],
            },
        ),
    ]
