# Generated by Django 5.2.3 on 2025-08-09 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talent_management', '0021_delete_trendingskill_remove_resume_aadhar_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='post_graduate_details',
            field=models.JSONField(blank=True, default=list, verbose_name='Post-Graduate Details'),
        ),
    ]
