# Generated by Django 5.2.3 on 2025-08-12 08:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talent_management', '0022_resume_post_graduate_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('TENTH_CERTIFICATE', '10th Certificate'), ('TWELFTH_CERTIFICATE', '12th Certificate'), ('DIPLOMA', 'Diploma Certificate'), ('DEGREE', 'Degree Certificate'), ('POST_GRADUATION', 'Post Graduation Certificate'), ('CERTIFICATION', 'General Certification'), ('INTERNSHIP', 'Internship Certificate'), ('SKILL', 'Skill Certificate'), ('OTHER', 'Other Document')], max_length=50, verbose_name='Document Type')),
                ('document_file', models.FileField(upload_to='resume_documents/', verbose_name='Document File')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Description')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('talent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resume_documents', to=settings.AUTH_USER_MODEL, verbose_name='Talent')),
            ],
            options={
                'verbose_name': 'Resume Document',
                'verbose_name_plural': 'Resume Documents',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
