# Generated by Django 5.2.3 on 2025-08-19 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talent_management', '0024_skillspassport'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skillspassport',
            options={'ordering': ['-created_at'], 'verbose_name': 'Skills Passport', 'verbose_name_plural': 'Skills Passports'},
        ),
        migrations.AddField(
            model_name='skillspassport',
            name='rated_certifications',
            field=models.JSONField(default=list, help_text="List of certification dicts with an added 'relevance_score' from AI analysis, e.g., [{'name': 'AWS Certified', 'relevance_score': 90}]"),
        ),
        migrations.AlterField(
            model_name='skillspassport',
            name='communication_skills_score',
            field=models.IntegerField(default=0, help_text='AI-generated score based on interview transcript analysis.'),
        ),
        migrations.AlterField(
            model_name='skillspassport',
            name='cultural_adaptability_score',
            field=models.IntegerField(default=0, help_text='AI-generated score for cultural fit and adaptability.'),
        ),
        migrations.AlterField(
            model_name='skillspassport',
            name='frameworks_tools',
            field=models.JSONField(default=list, help_text="List of dicts: [{'name': 'PyTorch', 'projects': 2, 'proficiency': 4}]"),
        ),
        migrations.AlterField(
            model_name='skillspassport',
            name='global_readiness_score',
            field=models.IntegerField(default=0, help_text='Overall weighted score for global readiness.'),
        ),
        migrations.AlterField(
            model_name='skillspassport',
            name='relocation_score',
            field=models.IntegerField(default=0, help_text='AI-generated score for relocation readiness.'),
        ),
        migrations.AlterField(
            model_name='skillspassport',
            name='specialization_scores',
            field=models.JSONField(default=dict, help_text="Dict of specializations and their scores from the interview, e.g., {'Machine Learning': 95}"),
        ),
        migrations.AlterField(
            model_name='skillspassport',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Generation'), ('COMPLETED', 'Completed Successfully'), ('FAILED', 'Generation Failed')], default='PENDING', max_length=50, verbose_name='Generation Status'),
        ),
        migrations.AlterField(
            model_name='skillspassport',
            name='technical_readiness_score',
            field=models.IntegerField(default=0, help_text='AI-generated score based on interview transcript and resume.'),
        ),
    ]
