# Generated by Django 5.2.3 on 2025-08-22 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talent_management', '0025_alter_skillspassport_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='employee_level',
            field=models.CharField(blank=True, choices=[('FRESHER', 'Fresher'), ('INTERN', 'Intern'), ('EXPERIENCED', 'Experienced')], max_length=200, null=True, verbose_name='Employee Level'),
        ),
    ]
