# Generated by Django 5.2.3 on 2025-06-19 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer_management', '0003_alter_company_industry_alter_company_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='resumes/'),
        ),
    ]
