# Generated by Django 5.2.3 on 2025-06-19 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer_management', '0002_alter_application_talent_savedjob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='industry',
            field=models.CharField(blank=True, choices=[('IT_SOFTWARE', 'IT/Software'), ('FINANCE', 'Finance'), ('HEALTHCARE', 'Healthcare'), ('EDUCATION', 'Education'), ('MANUFACTURING', 'Manufacturing'), ('RETAIL', 'Retail'), ('CONSULTING', 'Consulting'), ('MEDIA_ENTERTAINMENT', 'Media & Entertainment'), ('HOSPITALITY', 'Hospitality'), ('CONSTRUCTION', 'Construction'), ('GOVERNMENT', 'Government'), ('NON_PROFIT', 'Non-Profit'), ('E_COMMERCE', 'E-commerce'), ('TELECOMMUNICATIONS', 'Telecommunications'), ('AUTOMOTIVE', 'Automotive'), ('PHARMACEUTICALS', 'Pharmaceuticals'), ('ENERGY', 'Energy'), ('TRANSPORTATION_LOGISTICS', 'Transportation & Logistics'), ('FOOD_BEVERAGE', 'Food & Beverage'), ('REAL_ESTATE', 'Real Estate'), ('MARKETING_ADVERTISING', 'Marketing & Advertising'), ('OTHER', 'Other')], max_length=100, null=True, verbose_name='Industry'),
        ),
        migrations.AlterField(
            model_name='company',
            name='size',
            field=models.CharField(blank=True, choices=[('1-10', '1-10 employees'), ('11-50', '11-50 employees'), ('51-200', '51-200 employees'), ('201-500', '201-500 employees'), ('501-1000', '501-1000 employees'), ('1001-5000', '1001-5000 employees'), ('5000+', '5000+ employees')], max_length=50, null=True, verbose_name='Company Size'),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='experience_level',
            field=models.CharField(blank=True, choices=[('Entry-level', 'Entry Level (0-2 years)'), ('Mid-level', 'Mid Level (3-5 years)'), ('Senior-level', 'Senior Level (5+ years)'), ('Lead/Principal', 'Lead/Principal (8+ years)'), ('Executive', 'Executive (10+ years)')], max_length=50),
        ),
    ]
