# Generated by Django 5.2.3 on 2025-07-15 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer_management', '0004_application_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='ai_interview_session_data',
            field=models.JSONField(blank=True, help_text='Stores the serialized state of the AIInterviewer instance for this interview.', null=True),
        ),
        migrations.AddField(
            model_name='interview',
            name='ai_model_used',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='AI Model Used'),
        ),
        migrations.AddField(
            model_name='interview',
            name='identity_verified',
            field=models.BooleanField(default=False, help_text="Indicates if the candidate's identity was verified by proctoring"),
        ),
        migrations.AddField(
            model_name='interview',
            name='interview_duration_seconds',
            field=models.IntegerField(blank=True, null=True, verbose_name='Interview Duration (seconds)'),
        ),
        migrations.AddField(
            model_name='interview',
            name='interview_report_data',
            field=models.JSONField(blank=True, null=True, verbose_name='Detailed Interview Report Data'),
        ),
        migrations.AddField(
            model_name='interview',
            name='malpractice_details',
            field=models.JSONField(blank=True, null=True, verbose_name='Malpractice Incident Details'),
        ),
        migrations.AddField(
            model_name='interview',
            name='malpractice_events',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='List of Malpractice Events'),
        ),
        migrations.AddField(
            model_name='interview',
            name='malpractice_status',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Proctoring Malpractice Status'),
        ),
        migrations.AddField(
            model_name='interview',
            name='overall_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Overall Interview Score'),
        ),
        migrations.AddField(
            model_name='interview',
            name='started_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when the interview session actually started', null=True),
        ),
        migrations.AddField(
            model_name='interview',
            name='technical_specializations_assessed',
            field=models.JSONField(blank=True, null=True, verbose_name='Technical Specializations Assessed'),
        ),
        migrations.AlterField(
            model_name='interview',
            name='interview_status',
            field=models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('TERMINATED_MALPRACTICE', 'Terminated due to Malpractice'), ('CANCELLED', 'Cancelled'), ('error', 'Error')], default='SCHEDULED', max_length=50),
        ),
    ]
