# Generated by Django 5.2.3 on 2025-07-17 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer_management', '0005_interview_ai_interview_session_data_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interview',
            name='ai_interview_session_data',
        ),
        migrations.RemoveField(
            model_name='interview',
            name='ai_model_used',
        ),
        migrations.RemoveField(
            model_name='interview',
            name='identity_verified',
        ),
        migrations.RemoveField(
            model_name='interview',
            name='interview_duration_seconds',
        ),
        migrations.RemoveField(
            model_name='interview',
            name='interview_report_data',
        ),
        migrations.RemoveField(
            model_name='interview',
            name='malpractice_details',
        ),
        migrations.RemoveField(
            model_name='interview',
            name='malpractice_events',
        ),
        migrations.RemoveField(
            model_name='interview',
            name='malpractice_status',
        ),
        migrations.RemoveField(
            model_name='interview',
            name='overall_score',
        ),
        migrations.RemoveField(
            model_name='interview',
            name='started_at',
        ),
        migrations.RemoveField(
            model_name='interview',
            name='technical_specializations_assessed',
        ),
        migrations.AlterField(
            model_name='interview',
            name='interview_status',
            field=models.CharField(choices=[('Scheduled', 'Scheduled'), ('Completed', 'Completed'), ('Canceled', 'Canceled'), ('Rescheduled', 'Rescheduled')], default='Scheduled', max_length=50),
        ),
    ]
