# Generated by Django 5.2.3 on 2025-08-04 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer_management', '0007_alter_application_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('APPLIED', 'Applied'), ('REVIEWED', 'Reviewed'), ('SHORTLISTED', 'Shortlisted'), ('INTERVIEW_SCHEDULED', 'Interview Scheduled'), ('INTERVIEWED', 'Interviewed'), ('OFFER_EXTENDED', 'Offer Extended'), ('OFFER_ACCEPTED', 'Offer Accepted'), ('OFFER_REJECTED', 'Offer Rejected'), ('REJECTED', 'Rejected'), ('HIRED', 'Hired'), ('WITHDRAWN', 'Withdrawn'), ('DELETED', 'Deleted'), ('SCHEDULED', 'Scheduled')], default='APPLIED', max_length=50),
        ),
    ]
