# Generated by Django 5.2.3 on 2025-08-20 18:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer_management', '0008_alter_application_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewFeedback',
            fields=[
                ('interview', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='feedback_details', serialize=False, to='employer_management.interview')),
                ('technical_skills_rating', models.PositiveSmallIntegerField(blank=True, help_text='Rating from 1 (Poor) to 10 (Excellent)', null=True)),
                ('communication_skills_rating', models.PositiveSmallIntegerField(blank=True, help_text='Rating from 1 (Poor) to 10 (Excellent)', null=True)),
                ('cultural_fit_rating', models.PositiveSmallIntegerField(blank=True, help_text='Rating from 1 (Poor) to 10 (Excellent)', null=True)),
                ('strengths', models.TextField(blank=True, verbose_name="Candidate's Strengths")),
                ('weaknesses', models.TextField(blank=True, verbose_name='Areas for Improvement')),
                ('overall_comments', models.TextField(verbose_name='Overall Comments')),
                ('recommendation', models.CharField(choices=[('STRONG_HIRE', 'Strong Hire'), ('HIRE', 'Hire'), ('NO_HIRE', 'No Hire'), ('NOT_SURE', 'Not Sure / Needs More Review')], max_length=50, verbose_name='Overall Recommendation')),
                ('outcome', models.CharField(choices=[('PENDING', 'Pending'), ('PASSED', 'Passed'), ('FAILED', 'Failed')], default='PENDING', max_length=50, verbose_name='Final Outcome')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('interviewer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='given_feedback', to=settings.AUTH_USER_MODEL, verbose_name='Feedback Provided By')),
            ],
            options={
                'verbose_name': 'Interview Feedback',
                'verbose_name_plural': 'Interview Feedbacks',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
