# Generated by Django 5.2.3 on 2025-07-19 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(help_text='Description of the administrative action performed.', max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='When the action was performed.')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address from which the action was initiated.', null=True)),
                ('details', models.JSONField(blank=True, help_text='Additional JSON details about the action (e.g., old_value, new_value, affected_object_id).', null=True)),
            ],
            options={
                'verbose_name': 'Admin Activity Log',
                'verbose_name_plural': 'Admin Activity Logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='SystemHealthStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(help_text="Name of the system service (e.g., 'Aadhaar Integration', 'DigiLocker API')", max_length=100, unique=True)),
                ('status', models.CharField(choices=[('ONLINE', 'Online'), ('OFFLINE', 'Offline'), ('MAINTENANCE', 'Maintenance'), ('DEGRADED', 'Degraded'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', help_text='Current health status of the service', max_length=20)),
                ('last_checked', models.DateTimeField(auto_now=True, help_text='Timestamp of the last status update')),
                ('message', models.TextField(blank=True, help_text='Optional message about the service status (e.g., reason for downtime)', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this service status is actively monitored and displayed.')),
            ],
            options={
                'verbose_name': 'System Health Status',
                'verbose_name_plural': 'System Health Statuses',
                'ordering': ['service_name'],
            },
        ),
    ]
